#!/bin/bash

echo $@

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

sh $HOME/.xprofile

case $1 in
  gnome)
    exec gnome-session
    ;;
  awesome)
    exec awesome
    ;;
  *)
    exec dbus-launch xmonad
    ;;
esac
