#!/bin/bash
# These functions are defined for use from the command line by a human user as
# a convenience.
#
# This script has been tested on [Arch Linux][arch] with Bash 4.2.24.
#
# [arch]: http://www.archlinux.org

# ## Daemon Handling

# This function starts a daemon in the rc.d style. This could also have been
# defined using the rc.d command-line application, but this is more direct.
function start() {
  for arg in $@
  do
    sudo /etc/rc.d/$arg start
  done
}

# This function stops a daemon in the rc.d style. This could also have been
# defined using the rc.d command-line application, but this is more direct.
function stop() {
  for arg in $@
  do
    sudo /etc/rc.d/$arg stop
  done
}

# This function restarts a daemon in the rc.d style. This could also have been
# defined using the rc.d command-line application, but this is more direct.
function restart() {
  for arg in $@
  do
    sudo /etc/rc.d/$arg restart
  done
}

# This function reports on the status a daemon in the rc.d style. This could
# also have been defined using the rc.d command-line application, but this is
# more direct.
function status() {
  for     arg in $@
  do
    sudo /etc/rc.d/$arg status
  done
}

# ## Miscellaenous

# This method change the terminal title. This should be compatible with most
# emulators.
function chtitle() {
  echo -ne "\033]0;${1:-$TERM}\007";
}

# This function makes directory then changes directory into it. Very handy for
# the lazy.
function take() {
  mkdir -vp "$1" && cd "$_";
}

