#!/bin/bash
# Josh D Miller <josh@joshdmiller.com>
# With portions from:
#   - c00kiemon5ter (ivan.kanak@gmail.com) ~ under c00kiez License

# cd helper
function goto() { 
        [ -d "$1" ] && cd "$1" || cd "$(dirname "$1")"; 
}

## services handling
function start() {
        for arg in $@
        do
                sudo /etc/rc.d/$arg start
        done
}

function stop() {
        for arg in $@
        do
                sudo /etc/rc.d/$arg stop
        done
}

function restart() {
        for arg in $@
        do
                sudo /etc/rc.d/$arg restart
        done
}

function status() {
        for     arg in $@
        do
                sudo /etc/rc.d/$arg status
        done
}

# change terminal title
function chtitle() {
        echo -ne "\033]0;${1:-$TERM}\007";
}

# Makes directory then moves into it
function cdnew() {
            mkdir -vp "$1" && cd "$_";
}

# vim: nospell
